const fs = require('fs');
let code = fs.readFileSync('services/geminiService.ts', 'utf-8');

const oldStr = `MANUFACTURING JSON DETECTED. IGNORE DEFAULT GLOBAL STYLE.\\n\\n==================================\\nMANUFACTURING JSON (STRICT OVERRIDE)\\n==================================\\n\${settings.manufacturingJson}\\n\\nCRITICAL INSTRUCTION: You MUST strictly adhere to the guidelines and rules provided in the Manufacturing JSON above for EVERY prompt. All other style, character, and continuity guidelines are IGNORED in favor of this JSON. Put the stuff in prompts exactly like it instructs.\\n`;

const newStr = `MANUFACTURING JSON DETECTED. IGNORE DEFAULT GLOBAL STYLE.\\n\\n==================================\\nMANUFACTURING JSON (STRICT OVERRIDE)\\n==================================\\n\${settings.manufacturingJson}\\n\\nCRITICAL INSTRUCTION: You MUST strictly adhere to the guidelines and rules provided in the Manufacturing JSON above for EVERY prompt. All other style, character, and continuity guidelines are IGNORED in favor of this JSON.\\n\\nCRITICAL DIAGNOSTIC RULES FOR PROMPT GENERATION:\\n1. TOPIC & NARRATION AWARE: Do not just generate a generic shot of the topic. Ask "What exactly is the narrator saying right here?" and show the physical event/object/person/process.\\n2. SCENE FUNCTION: Every shot must have a job (e.g. if narration says "cutters wear out", show worn cutters, not just the whole tunnel).\\n3. VISUAL VOCABULARY: Rotate between Machine, People, Process, Infrastructure, Environment, Geography, Human consequence. Keep it consistent with the JSON.\\n4. SHOT DIVERSITY: Different visual purposes. Don't just change the camera angle on the identical underlying visual content.\\n5. ESTABLISHING VS EXPLANATORY: Use establishing shots to show "where we are" and explanatory shots to show "what is happening" (close-ups, actions).\\n6. PRESERVE STATE (CONTINUITY): Dimensions, depth, environment color, etc., must carry over. No state loss across generation!\\n7. LOCKED VS CREATIVE: LOCKED facts (dimensions, geography, machinery, materials) CANNOT change. CREATIVE variables (camera, lighting, composition) CAN change.\\n8. TEMPORAL PROGRESSION: Visuals must evolve along a timeline (preparation -> excavation -> problem -> maintenance -> completion).\\n9. SHOT ALLOCATION: Important technical events get highly specific shots; trivial transitions get fewer generic shots.\\n10. DO NOT REUSE UNLESS JUSTIFIED: Each shot must introduce a new visual subject, action, environment, state, or interaction unless continuity is required.\\n11. STRONG POSITIVE SPECIFICATION: Tell the model exactly what SHOULD be there instead of just relying on negative prompts.\\n12. SHOT-LEVEL SEMANTICS: For every generated shot, define its Narrative Purpose, Primary Subject, Action, Environment, Technical Facts, Human Presence, Visual State, Cinematography, and Continuity.\\n`;

code = code.replace(oldStr, newStr);

// Also update the regenerateClip instruction to include the new rules
const oldRegenStr = `"\\n\\n==================================\\nMANUFACTURING JSON (STRICT OVERRIDE)\\n==================================\\n" + settings.manufacturingJson + "\\n\\nCRITICAL INSTRUCTION: You MUST strictly adhere to the guidelines and rules provided in the Manufacturing JSON above."`;

const newRegenStr = `"\\n\\n==================================\\nMANUFACTURING JSON (STRICT OVERRIDE)\\n==================================\\n" + settings.manufacturingJson + "\\n\\nCRITICAL INSTRUCTION: You MUST strictly adhere to the guidelines and rules provided in the Manufacturing JSON above.\\n\\nCRITICAL DIAGNOSTIC RULES:\\n1. TOPIC & NARRATION AWARE\\n2. SCENE FUNCTION\\n3. VISUAL VOCABULARY\\n4. SHOT DIVERSITY\\n5. ESTABLISHING VS EXPLANATORY\\n6. PRESERVE STATE (CONTINUITY)\\n7. LOCKED VS CREATIVE\\n8. TEMPORAL PROGRESSION\\n9. SHOT ALLOCATION\\n10. DO NOT REUSE UNLESS JUSTIFIED\\n11. STRONG POSITIVE SPECIFICATION\\n12. SHOT-LEVEL SEMANTICS"`;

code = code.replace(oldRegenStr, newRegenStr);

fs.writeFileSync('services/geminiService.ts', code);
console.log("Patched Manufacturing Rules in geminiService.ts");
